name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: neofetch
      run: neofetch
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
  showinfo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: sudo reboot
      run: sudo reboot
